Repository openshift/must-gather-operator, pull requests merged in 2025-07, with the labels that each got.

#243 Boilerplate update 2-bbf78011d6159c4b4f34bbdd9e10d188f809234d
  .ci-operator.yaml
  OWNERS_ALIASES
  boilerplate/_data/backing-image-tag
  boilerplate/_data/last-boilerplate-commit
  boilerplate/openshift/golang-osd-operator-osde2e/OWNERS
  boilerplate/openshift/golang-osd-operator-osde2e/README.md
  boilerplate/openshift/golang-osd-operator-osde2e/e2e-image-build-push.sh
  boilerplate/openshift/golang-osd-operator-osde2e/e2e-template.yml
  boilerplate/openshift/golang-osd-operator-osde2e/project.mk
  boilerplate/openshift/golang-osd-operator-osde2e/standard.mk
  boilerplate/openshift/golang-osd-operator-osde2e/update
  boilerplate/openshift/golang-osd-operator/OWNERS_ALIASES
  boilerplate/openshift/golang-osd-operator/prow-config
  build/Dockerfile
  hack/olm-registry/olm-artifacts-template.yaml
  test/e2e/README.md
  test/e2e/e2e-template.yml
Labels: lgtm, approved

#244 bp update
  boilerplate/_data/last-boilerplate-commit
  boilerplate/generated-includes.mk
  boilerplate/openshift/golang-osd-e2e/OWNERS
  boilerplate/openshift/golang-osd-e2e/README.md
  boilerplate/openshift/golang-osd-e2e/e2e-template.yml
  boilerplate/openshift/golang-osd-e2e/project.mk
  boilerplate/openshift/golang-osd-e2e/standard.mk
  boilerplate/openshift/golang-osd-e2e/update
  boilerplate/update.cfg
  test/e2e/e2e-template.yml
Labels: lgtm, approved

#245 MG-39: Use namespace `must-gather-operator` for deploying operator
  config/config.go
  config/metadata/additional-labels.txt
  config/templates/csv-template.yaml
  config/templates/must-gather-operator-csv-template.yaml
  controllers/mustgather/mustgather_controller.go
  controllers/mustgather/mustgather_controller_test.go
  deploy/03_must-gather-operator.ClusterRoleBinding.yaml
  deploy/06_must-gather-admin.ClusterRoleBinding.yaml
  deploy/07_prometheus-k8s.Role.yaml
  deploy/08_prometheus-k8s.RoleBinding.yaml
  deploy/99_must-gather-operator.Deployment.yaml
  examples/other_resources/00_openshift-must-gather-operator.Namespace.yaml
  examples/other_resources/01_must-gather-operator.ServiceAccount.yaml
  examples/other_resources/03_must-gather-operator.ClusterRoleBinding.yaml
  examples/other_resources/04_must-gather-admin.ServiceAccount.yaml
  examples/other_resources/06_must-gather-admin.ClusterRoleBinding.yaml
  hack/olm-registry/olm-artifacts-template.yaml
  main.go
Labels: lgtm, approved, jira/valid-reference

#249 MG-36: Add support for SFTP upload on proxy setup
  build/Dockerfile
  build/bin/upload
Labels: lgtm, approved, qe-approved, jira/valid-reference
